/** Identifiants stables des canaux IPC (main ↔ renderer). */
export const IpcChannels = {
  APP_GET_INFO: 'app:get-info',
  MODE_GET: 'mode:get',
  MODE_SET: 'mode:set',
  MODE_CLEAR: 'mode:clear',
  SERVER_START: 'server:start',
  SERVER_STOP: 'server:stop',
  SERVER_STATUS: 'server:status',
  CLIENT_CONNECT: 'client:connect',
  CLIENT_DISCONNECT: 'client:disconnect',
  CLIENT_STATUS: 'client:status',
  SYNC_FLUSH: 'sync:flush',
  SYNC_QUEUE_SIZE: 'sync:queue-size',
  SYNC_REGISTERED_COUNT: 'sync:registered-count',
  SYNC_QUEUE_CLEAR: 'sync:queue-clear',
  JUDOKA_CREATE: 'judoka:create',
  JUDOKA_UPDATE: 'judoka:update',
  JUDOKA_DELETE: 'judoka:delete',
  JUDOKA_LIST: 'judoka:list',
  JUDOKA_SEARCH: 'judoka:search',
  JUDOKA_CREATORS: 'judoka:creators',
  JUDOKA_DELETE_CREATOR: 'judoka:delete-creator',
  JUDOKA_CLUB_NAMES: 'judoka:club-names',
  JUDOKA_RESET: 'judoka:reset',
  JUDOKA_GET: 'judoka:get',
  JUDOKA_CHECK_DUPLICATE: 'judoka:check-duplicate',
  DASHBOARD_STATS: 'dashboard:stats',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  BACKUP_EXPORT: 'backup:export',
  BACKUP_PICK: 'backup:pick',
  BACKUP_IMPORT: 'backup:import',
  BADGE_TEMPLATE_GET: 'badge:template-get',
  BADGE_TEMPLATE_SET: 'badge:template-set',
  BADGE_TEMPLATE_LIST: 'badge:template-list',
  BADGE_TEMPLATE_CREATE: 'badge:template-create',
  BADGE_TEMPLATE_DELETE: 'badge:template-delete',
  BADGE_TEMPLATE_SET_ACTIVE: 'badge:template-set-active',
  PDF_EXPORT_BADGES: 'pdf:export-badges',
  PRINT_BADGE: 'print:badge',
  PHOTO_SAVE_DATA_URL: 'photo:save-data-url',
  PHOTO_IMPORT_FILE: 'photo:import-file',
  DIALOG_OPEN_IMAGE: 'dialog:open-image',
  DIALOG_SAVE_PDF: 'dialog:save-pdf',
  PRINT_LIST_PRINTERS: 'print:list-printers',
  BADGE_IMPORT_ASSET: 'badge:import-asset',
  LOG_LIST: 'log:list',
  LOG_CLEAR: 'log:clear',
  USER_LIST: 'user:list',
  USER_CREATE: 'user:create',
  USER_DELETE: 'user:delete',
  NETWORK_LOCAL_INFO: 'network:local-info',
  PHOTO_READ_DATA_URL: 'photo:read-data-url',
  SYNC_QUEUE_LIST: 'sync:queue-list'
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
